#!/bin/sh

git config --global alias.br 'branch'
git config --global alias.co 'checkout'
git config --global alias.ci 'commit'
git config --global alias.st 'status'
git config --global alias.df 'diff'
git config --global alias.dfs 'diff --staged'
git config --global alias.amend 'commit --amend'
git config --global alias.unstage 'reset HEAD --'
git config --global alias.chmodx 'update-index --chmod=+x'
git config --global alias.chmod-x 'update-index --chmod=-x'
git config --global alias.reset-hom 'reset --hard origin/master'
git config --global alias.logo 'log --oneline'
git config --global alias.logs 'log --oneline --stat'
git config --global alias.logg 'log --oneline --graph --decorate --all'
git config --global alias.last 'log -1 --stat'
git config --global alias.lg "log --graph --all --pretty=tformat:'%C(auto)%h%d%Creset %s %C(dim green)(%cr) %C(cyan)<%an>%Creset'"
git config --global alias.p 'push'
git config --global alias.pf 'push --force'
git config --global alias.root 'rev-parse --show-toplevel'
git config --global alias.alias  ' ! git config --get-regexp ^alias\\. | sed -e s/^alias\\.// -e s/\\ /\\ =\\ /'
